import "./globals.css";
import { DarkModeProvider } from "./context/DarkModeContext";

export const metadata = {
  title: "My Portfolio",
  description: "Generated by Next.js",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="scroll-smooth">
      <body>
        <DarkModeProvider>{children}</DarkModeProvider>
      </body>
    </html>
  );
}
